imu_topic: /eduard/imu
imu_livox_topic: /livox/imu
pointcloud_topic: /eduard/livox/scan/points
lidar_topic: /eduard/livox/livox_custom_msg
body_frame: body
world_frame: map
print_time_cost: false

lidar_filter_num: 3
lidar_min_range: 0.2
lidar_max_range: 40.0
scan_resolution: 0.1
map_resolution: 0.3

cube_len: 300
det_range: 60
move_thresh: 0.2

na: 0.01
ng: 0.01
nba: 0.0001
nbg: 0.0001

imu_init_num: 20
near_search_num: 5
ieskf_max_iter: 5

gravity_align: false
esti_il: false

# Livox Mid 360
# r_il: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
# t_il: [-0.011, -0.02329, 0.04412]
# t_il: [0.0, 0.0, 0.0]

# Gazebo Simulation with Eduard
r_il: [0.9063077869, 0, 0.4226182620, 0, 1, 0, -0.4226182620, 0, 0.9063077869]
t_il: [0.145, 0, 0.165]

lidar_cov_inv: 1000.0
